### ISSUE TITLE
Crash when growing Corn in BTM Planter

### ISSUE THREAD

**Issue by nmarshall23** [cleverpanda/SimpleCorn#10]
I've posted this bug on BeetoGuy/BetterWithMods#567 Issues Page. 

They inform me that the problem is on your end. That: 
`world.getBlockState(pos.down()).getBlock().isFertile(world, pos)` should be `world.getBlockState(pos.down()).getBlock().isFertile(world, pos.down())`

**Comment by cleverpanda** [comment]
Fixed
