### ISSUE TITLE
Question of submission

### ISSUE THREAD

**Issue by meitangdehulu** [cleverpanda/SimpleCorn#17]
Can not submit changes, display blank.
https://i.loli.net/2018/01/29/5a6ecb803f297.png

**Comment by cleverpanda** [comment]
I'm not sure what that means, but you can put the file in pastebin or dropbox or send it to me on curseforge message

**Comment by meitangdehulu** [comment]
1.12lang：
https://www.dropbox.com/s/dco263684zfv97d/zh_CN.lang
