### ISSUE TITLE
BlockCorn not using Forge growth hooks, breaking some mod compatibility

### ISSUE THREAD

**Issue by Stormwind99** [cleverpanda/SimpleCorn#18]
https://minecraft.curseforge.com/projects/simple-corn/issues/16

From Forstride:

"The corn block itself doesn't seem to be using Forge hooks for the growth event, meaning other mods can't cancel it if needed.  We're adding seasonal crop support to our mod, Serene Seasons, and I actually used Simple Corn as a basic test for mod support, but it doesn't work properly without the Forge hooks (So corn will still grow naturally in Winter for example, which shouldn't happen)

See line 85 in BlockCrops if you need to know how it's done."

**Comment by Stormwind99** [comment]
I'll submit a pull request with a fix.

See https://github.com/Stormwind99/SimpleCorn/tree/18-blockcorn-forge-events

**Comment by Stormwind99** [comment]
Fixed in #19

**Comment by cleverpanda** [comment]
Thank you so much for this. I've been vary busy recently and unable to give my projects the attention they need. :) I will try to review and merge/build/release this tonight. (Central time, 6/27/18)
