### ISSUE TITLE
ProxyInjector can not access a member of class panda.corn.proxy.ServerProxy with modifiers "private"

### ISSUE THREAD

**Issue by coolsimulations** [cleverpanda/SimpleCorn#24]
Playing with SimpleCorn 2.5.5 on 1.12.2 on my server and am having this crash upon starting up.

[crash-2019-04-22_15.45.23-server.txt](https://github.com/cleverpanda/SimpleCorn/files/3102338/crash-2019-04-22_15.45.23-server.txt)

**Comment by cleverpanda** [comment]
Whoops. thank you, just fix this, waiting on Curse to approve
