### ISSUE TITLE
1.10.2 Crash while exploring

### ISSUE THREAD

**Issue by Kashdeya** [cleverpanda/SimpleCorn#9]
Walking around exploring new map and got this crash. 

https://pastebin.com/xF7nDHuT

**Comment by raphydaphy** [comment]
I had the same crash https://pastebin.com/wbF6Yy0s

**Comment by cjm721** [comment]
Still exists on 1.11.2

https://gist.github.com/cjm721/d7efe3f23370ef144ddcc82622ed9c1f

**Comment by Sunconure11** [comment]
Also having it, too.

**Comment by cleverpanda** [comment]
Please know that I'm still trying to fix this bug. It's been very hard to reproduce but I am still working on it. Thank you for your patience.

**Comment by HeberonYT** [comment]
I have the same error in exploring my world.
I hope I can solve it soon.
-Minecraft 1.10.2
-SimpleCorn1.10-2.1.6.jar

Crash Report: `https://pastebin.com/raw/qdfNJWMM`

**Comment by cleverpanda** [comment]
Threw in a null check V2.2.0
